import Navbar from '../components/Navbar';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import NextAuthProvider from '@/providers/provider';
import CheckLogin from '@/components/CheckLogin';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Bookmarkt',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
  session: any;
}

export default function RootLayout({ children, session }: Props) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Navbar />
          <div className="px-min-nav">
            {children}
            {/* <Footer /> */}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
