import getCurrentUser from '@/actions/getCurrentUser';
import Navbar from '../components/Navbar/Navbar';
import './globals.css';
import ConditionalNav from '@/components/ConditionalNav';

export const metadata = {
  title: 'Bookmarkt',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: Props) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body>
        <Navbar currentUser={currentUser} />
        <ConditionalNav navOn />
        <div>{children}</div>
      </body>
    </html>
  );
}
